package com.zhouqi.entity;

import java.io.Serializable;
import java.util.Date;

public class CfgTask implements Serializable, Cloneable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.CFG_TASK_ID
	 *
	 * @mbggenerated
	 */
	private Long cfgTaskId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.TASK_NAME
	 *
	 * @mbggenerated
	 */
	private String taskName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.CFG_TASK_TYPE_CODE
	 *
	 * @mbggenerated
	 */
	private String cfgTaskTypeCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.TRIGGER_TYPE
	 *
	 * @mbggenerated
	 */
	private String triggerType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.TRIGGER_EXPR
	 *
	 * @mbggenerated
	 */
	private String triggerExpr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.PRIPORITY
	 *
	 * @mbggenerated
	 */
	private Integer pripority;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.CREATE_USER
	 *
	 * @mbggenerated
	 */
	private String createUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.TASK_STATE
	 *
	 * @mbggenerated
	 */
	private String taskState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.REMARKS
	 *
	 * @mbggenerated
	 */
	private String remarks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.START_DATE
	 *
	 * @mbggenerated
	 */
	private Date startDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.END_DATE
	 *
	 * @mbggenerated
	 */
	private Date endDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.JOB_EXPR
	 *
	 * @mbggenerated
	 */
	private String jobExpr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.JOB_TYPE
	 *
	 * @mbggenerated
	 */
	private String jobType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.TASK_PARAMS
	 *
	 * @mbggenerated
	 */
	private String taskParams;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cfg_task.TASK_GROUP
	 *
	 * @mbggenerated
	 */
	private String taskGroup;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table cfg_task
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.CFG_TASK_ID
	 *
	 * @return the value of cfg_task.CFG_TASK_ID
	 *
	 * @mbggenerated
	 */
	public Long getCfgTaskId() {
		return cfgTaskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.CFG_TASK_ID
	 *
	 * @param cfgTaskId
	 *            the value for cfg_task.CFG_TASK_ID
	 *
	 * @mbggenerated
	 */
	public void setCfgTaskId(Long cfgTaskId) {
		this.cfgTaskId = cfgTaskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.TASK_NAME
	 *
	 * @return the value of cfg_task.TASK_NAME
	 *
	 * @mbggenerated
	 */
	public String getTaskName() {
		return taskName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.TASK_NAME
	 *
	 * @param taskName
	 *            the value for cfg_task.TASK_NAME
	 *
	 * @mbggenerated
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName == null ? null : taskName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.CFG_TASK_TYPE_CODE
	 *
	 * @return the value of cfg_task.CFG_TASK_TYPE_CODE
	 *
	 * @mbggenerated
	 */
	public String getCfgTaskTypeCode() {
		return cfgTaskTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.CFG_TASK_TYPE_CODE
	 *
	 * @param cfgTaskTypeCode
	 *            the value for cfg_task.CFG_TASK_TYPE_CODE
	 *
	 * @mbggenerated
	 */
	public void setCfgTaskTypeCode(String cfgTaskTypeCode) {
		this.cfgTaskTypeCode = cfgTaskTypeCode == null ? null : cfgTaskTypeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.TRIGGER_TYPE
	 *
	 * @return the value of cfg_task.TRIGGER_TYPE
	 *
	 * @mbggenerated
	 */
	public String getTriggerType() {
		return triggerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.TRIGGER_TYPE
	 *
	 * @param triggerType
	 *            the value for cfg_task.TRIGGER_TYPE
	 *
	 * @mbggenerated
	 */
	public void setTriggerType(String triggerType) {
		this.triggerType = triggerType == null ? null : triggerType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.TRIGGER_EXPR
	 *
	 * @return the value of cfg_task.TRIGGER_EXPR
	 *
	 * @mbggenerated
	 */
	public String getTriggerExpr() {
		return triggerExpr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.TRIGGER_EXPR
	 *
	 * @param triggerExpr
	 *            the value for cfg_task.TRIGGER_EXPR
	 *
	 * @mbggenerated
	 */
	public void setTriggerExpr(String triggerExpr) {
		this.triggerExpr = triggerExpr == null ? null : triggerExpr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.PRIPORITY
	 *
	 * @return the value of cfg_task.PRIPORITY
	 *
	 * @mbggenerated
	 */
	public Integer getPripority() {
		return pripority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.PRIPORITY
	 *
	 * @param pripority
	 *            the value for cfg_task.PRIPORITY
	 *
	 * @mbggenerated
	 */
	public void setPripority(Integer pripority) {
		this.pripority = pripority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.CREATE_USER
	 *
	 * @return the value of cfg_task.CREATE_USER
	 *
	 * @mbggenerated
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.CREATE_USER
	 *
	 * @param createUser
	 *            the value for cfg_task.CREATE_USER
	 *
	 * @mbggenerated
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.TASK_STATE
	 *
	 * @return the value of cfg_task.TASK_STATE
	 *
	 * @mbggenerated
	 */
	public String getTaskState() {
		return taskState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.TASK_STATE
	 *
	 * @param taskState
	 *            the value for cfg_task.TASK_STATE
	 *
	 * @mbggenerated
	 */
	public void setTaskState(String taskState) {
		this.taskState = taskState == null ? null : taskState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.CREATE_DATE
	 *
	 * @return the value of cfg_task.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.CREATE_DATE
	 *
	 * @param createDate
	 *            the value for cfg_task.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.REMARKS
	 *
	 * @return the value of cfg_task.REMARKS
	 *
	 * @mbggenerated
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.REMARKS
	 *
	 * @param remarks
	 *            the value for cfg_task.REMARKS
	 *
	 * @mbggenerated
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.START_DATE
	 *
	 * @return the value of cfg_task.START_DATE
	 *
	 * @mbggenerated
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.START_DATE
	 *
	 * @param startDate
	 *            the value for cfg_task.START_DATE
	 *
	 * @mbggenerated
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.END_DATE
	 *
	 * @return the value of cfg_task.END_DATE
	 *
	 * @mbggenerated
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.END_DATE
	 *
	 * @param endDate
	 *            the value for cfg_task.END_DATE
	 *
	 * @mbggenerated
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.JOB_EXPR
	 *
	 * @return the value of cfg_task.JOB_EXPR
	 *
	 * @mbggenerated
	 */
	public String getJobExpr() {
		return jobExpr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.JOB_EXPR
	 *
	 * @param jobExpr
	 *            the value for cfg_task.JOB_EXPR
	 *
	 * @mbggenerated
	 */
	public void setJobExpr(String jobExpr) {
		this.jobExpr = jobExpr == null ? null : jobExpr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.JOB_TYPE
	 *
	 * @return the value of cfg_task.JOB_TYPE
	 *
	 * @mbggenerated
	 */
	public String getJobType() {
		return jobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.JOB_TYPE
	 *
	 * @param jobType
	 *            the value for cfg_task.JOB_TYPE
	 *
	 * @mbggenerated
	 */
	public void setJobType(String jobType) {
		this.jobType = jobType == null ? null : jobType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.TASK_PARAMS
	 *
	 * @return the value of cfg_task.TASK_PARAMS
	 *
	 * @mbggenerated
	 */
	public String getTaskParams() {
		return taskParams;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.TASK_PARAMS
	 *
	 * @param taskParams
	 *            the value for cfg_task.TASK_PARAMS
	 *
	 * @mbggenerated
	 */
	public void setTaskParams(String taskParams) {
		this.taskParams = taskParams == null ? null : taskParams.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cfg_task.TASK_GROUP
	 *
	 * @return the value of cfg_task.TASK_GROUP
	 *
	 * @mbggenerated
	 */
	public String getTaskGroup() {
		return taskGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cfg_task.TASK_GROUP
	 *
	 * @param taskGroup
	 *            the value for cfg_task.TASK_GROUP
	 *
	 * @mbggenerated
	 */
	public void setTaskGroup(String taskGroup) {
		this.taskGroup = taskGroup == null ? null : taskGroup.trim();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (cfgTaskId ^ (cfgTaskId >>> 32));
		result = prime * result + ((cfgTaskTypeCode == null) ? 0 : cfgTaskTypeCode.hashCode());
		result = prime * result + ((endDate == null) ? 0 : endDate.hashCode());
		result = prime * result + ((jobExpr == null) ? 0 : jobExpr.hashCode());
		result = prime * result + ((jobType == null) ? 0 : jobType.hashCode());
		result = prime * result + (int) (pripority ^ (pripority >>> 32));
		result = prime * result + ((startDate == null) ? 0 : startDate.hashCode());
		result = prime * result + ((taskState == null) ? 0 : taskState.hashCode());
		result = prime * result + ((taskGroup == null) ? 0 : taskGroup.hashCode());
		result = prime * result + ((taskName == null) ? 0 : taskName.hashCode());
		result = prime * result + ((taskParams == null) ? 0 : taskParams.hashCode());
		result = prime * result + ((triggerExpr == null) ? 0 : triggerExpr.hashCode());
		result = prime * result + ((triggerType == null) ? 0 : triggerType.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CfgTask other = (CfgTask) obj;
		if (cfgTaskId != other.cfgTaskId)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "CfgTask [cfgTaskId=" + cfgTaskId + ", taskName=" + taskName + ", cfgTaskTypeCode=" + cfgTaskTypeCode + ", triggerType=" + triggerType
				+ ", triggerExpr=" + triggerExpr + ", pripority=" + pripority + ", createUser=" + createUser + ", taskState=" + taskState + ", createDate="
				+ createDate + ", remarks=" + remarks + ", startDate=" + startDate + ", endDate=" + endDate + ", jobType=" + jobType + ", jobExpr=" + jobExpr
				+ ", taskGroup=" + taskGroup + "]";
	}

	@Override
	public Object clone() {
		try {
			return super.clone();
		} catch (CloneNotSupportedException e) {
			
		}
		return null;
	}

	public boolean valueEquals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CfgTask other = (CfgTask) obj;
		if (cfgTaskId != other.cfgTaskId)
			return false;
		if (cfgTaskTypeCode == null) {
			if (other.cfgTaskTypeCode != null)
				return false;
		} else if (!cfgTaskTypeCode.equals(other.cfgTaskTypeCode))
			return false;
		if (endDate == null) {
			if (other.endDate != null)
				return false;
		} else if (!endDate.equals(other.endDate))
			return false;
		if (jobExpr == null) {
			if (other.jobExpr != null)
				return false;
		} else if (!jobExpr.equals(other.jobExpr))
			return false;
		if (jobType == null) {
			if (other.jobType != null)
				return false;
		} else if (!jobType.equals(other.jobType))
			return false;
		if (pripority != other.pripority)
			return false;
		if (startDate == null) {
			if (other.startDate != null)
				return false;
		} else if (!startDate.equals(other.startDate))
			return false;
		if (taskState == null) {
			if (other.taskState != null)
				return false;
		} else if (!taskState.equals(other.taskState))
			return false;
		if (taskGroup == null) {
			if (other.taskGroup != null)
				return false;
		} else if (!taskGroup.equals(other.taskGroup))
			return false;
		if (taskName == null) {
			if (other.taskName != null)
				return false;
		} else if (!taskName.equals(other.taskName))
			return false;
		if (taskParams == null) {
			if (other.taskParams != null)
				return false;
		} else if (!taskParams.equals(other.taskParams))
			return false;
		if (triggerExpr == null) {
			if (other.triggerExpr != null)
				return false;
		} else if (!triggerExpr.equals(other.triggerExpr))
			return false;
		if (triggerType == null) {
			if (other.triggerType != null)
				return false;
		} else if (!triggerType.equals(other.triggerType))
			return false;
		return true;
	}
}