package com.zhouqi.dao;


import com.zhouqi.entity.CfgTaskLog;

public interface CfgTaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_task_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_task_log
     *
     * @mbggenerated
     */
    int insert(CfgTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_task_log
     *
     * @mbggenerated
     */
    int insertSelective(CfgTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_task_log
     *
     * @mbggenerated
     */
    CfgTaskLog selectByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_task_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_task_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgTaskLog record);
}